movieCreate:
  handler: src/functions/movie.functions.create
  timeout: 30
  events:
    - http:
        method: POST
        path: movie
        cors: true
        authorizer:
          name: authorizer
          resultTtlInSeconds: 0

movieGet:
  handler: src/functions/movie.functions.index
  timeout: 30
  events:
    - http:
        method: GET
        path: movie
        cors: true
        authorizer:
          name: authorizer
          resultTtlInSeconds: 0

movieDelete:
  handler: src/functions/movie.functions.destroy
  timeout: 30
  events:
    - http:
        method: DELETE
        path: movie/{id}
        cors: true
        authorizer:
          name: authorizer
          resultTtlInSeconds: 0

movieUpdate:
  handler: src/functions/movie.functions.update
  timeout: 30
  events:
    - http:
        method: PUT
        path: movie/{id}
        cors: true
        authorizer:
          name: authorizer
          resultTtlInSeconds: 0

movieFind:
  handler: src/functions/movie.functions.find
  timeout: 30
  events:
    - http:
        method: GET
        path: movie/{id}
        cors: true
        authorizer:
          name: authorizer
          resultTtlInSeconds: 0
